workflows:
  react-native-ios:
    name: iOS Build
    environment:
      vars:
        NODE_ENV: development
      flutter: false
      xcode: latest
      cocoapods: default
      ruby: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build iOS
        script: |
          npx eas build -p ios --profile preview
    artifacts:
      - build/ios/*.ipa
