export const dataList = [
    {
        id: '1',
        from: 'Chicago, IL',
        to: 'Atlanta, GA',
        age: 4,
        size: '53 ft',
        weight: '40,000 lbs',
        date: '09/25',
    },
    {
        id: '2',
        from: 'Chicago, IL',
        to: 'Atlanta, GA',
        age: 4,
        size: '53 ft',
        weight: '40,000 lbs',
        date: '09/25',
    },
    {
        id: '3',
        from: 'Chicago, IL',
        to: 'Atlanta, GA',
        age: 4,
        size: '53 ft',
        weight: '40,000 lbs',
        date: '09/25',
    },
    {
        id: '4',
        from: 'Chicago, IL',
        to: 'Atlanta, GA',
        age: 4,
        size: '53 ft',
        weight: '40,000 lbs',
        date: '09/25',
    },
    {
        id: '5',
        from: 'Chicago, IL',
        to: 'Atlanta, GA',
        age: 4,
        size: '53 ft',
        weight: '40,000 lbs',
        date: '09/25',
    },
    {
        id: '6',
        from: 'Chicago, IL',
        to: 'Atlanta, GA',
        age: 4,
        size: '53 ft',
        weight: '40,000 lbs',
        date: '09/25',
    },
    {
        id: '7',
        from: 'Chicago, IL',
        to: 'Atlanta, GA',
        age: 4,
        size: '53 ft',
        weight: '40,000 lbs',
        date: '09/25',
    },
    {
        id: '8',
        from: 'Chicago, IL',
        to: 'Atlanta, GA',
        age: 4,
        size: '53 ft',
        weight: '40,000 lbs',
        date: '09/25',
    },
]

export const LoadingData = [
    {
        id: '1',
        from: 'Chicago, IL',
        to: 'Atlanta, GA',
        age: 4,
        size: '53 ft',
        weight: '40,000 lbs',
        date: '09/25',
    },
]
